version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${CONTAINER_ENV}"
      XDEBUG_HOST: ${XDEBUG_HOST}
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/logs:/var/log/mysql
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

networks:
  slnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
