version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    environment:
      CONTAINER_ENV: "${CONTAINER_ENV}"
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
networks:
  slnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
